### ISSUE TITLE
Deprecation Errors

### ISSUE THREAD

**Issue by ijy** [familiar-studio/craft-image-color#6]
I'm running Craft 2.6.291 (current latest) and I'm getting a few deprecation errors on installation:

Message
The “hook” prefix on the Craft\ImageColorPlugin::hookAddTwigExtension() method name has been deprecated. It should be renamed to addTwigExtension().    

Origin
/var/sites/path/to/site/craft/app/services/PluginsService.php (586)

**Comment by ghost** [comment]
I'm also having this issue. I would love it if this got fixed...

**Comment by keithmancuso** [comment]
fixed thanks to a pull request!
